version: '3'

services:
  # logger:
  #   build: ./logger
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - broker
  #   networks:
  #     - desafio-network

  # users:
  #   build: ./accounts-auth
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - broker
  #   networks:
  #     - desafio-network

  mongo:
    image: mongo
    restart: on-failure
    env_file: ./mongo.env
    ports:
      - '27017:27017'
    volumes:
      - ./database/data/mongo/:/data/db
    networks:
      - desafio-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - desafio-network

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - desafio-network

networks:
  desafio-network:
    name: external-network
    external: true
